/**
 * MineGuard360 Shared Constants & Default Configurations
 */

import { SAFETY_CONFIG } from "../safety/safetyConfig";
import { ScenarioType } from "../types";

export { SAFETY_CONFIG };

export const DEFAULT_BLOCKS = [
  {
    blockId: "B1",
    name: "Blind Curve (Sector 4)",
    type: "PHYSICAL" as const,
    category: "BLIND_CURVE" as const,
    restricted: false,
    lengthM: 120,
    maxOccupancy: 2,
    occupancyState: "OCCUPIED" as const,
    currentOccupants: ["V01"],
    protectedSeparationM: 25,
    boundarySensors: "LD2401-A / LD2401-B ONLINE",
    weather: "NORMAL" as const,
    roadCondition: "DRY" as const,
    fogDensityPercent: 15,
    visibilityMeters: 165,
    visibility: "GOOD" as const,
    movementAuthority: "AUTHORIZED" as const,
    tokenStatus: "VALID" as const,
  },
  {
    blockId: "B2",
    name: "Narrow Haul Road",
    type: "VIRTUAL" as const,
    category: "NARROW_ROAD" as const,
    restricted: false,
    lengthM: 80,
    maxOccupancy: 1,
    occupancyState: "FREE" as const,
    currentOccupants: [],
    protectedSeparationM: 30,
    boundarySensors: "VIRTUAL BEACON ONLINE",
    weather: "DENSE_FOG" as const,
    roadCondition: "WET" as const,
    fogDensityPercent: 85,
    visibilityMeters: 15,
    visibility: "POOR" as const,
    movementAuthority: "AUTHORIZED" as const,
    tokenStatus: "VALID" as const,
  },
  {
    blockId: "B3",
    name: "Pit Junction Cross",
    type: "PHYSICAL" as const,
    category: "JUNCTION" as const,
    restricted: false,
    lengthM: 50,
    maxOccupancy: 1,
    occupancyState: "FREE" as const,
    currentOccupants: [],
    protectedSeparationM: 40,
    boundarySensors: "LD2401-C ONLINE",
    weather: "NORMAL" as const,
    roadCondition: "DRY" as const,
    fogDensityPercent: 10,
    visibilityMeters: 180,
    visibility: "GOOD" as const,
    movementAuthority: "AUTHORIZED" as const,
    tokenStatus: "VALID" as const,
  },
  {
    blockId: "B4",
    name: "Highwall Berm Descent",
    type: "PHYSICAL" as const,
    category: "HIGHWALL_EDGE" as const,
    restricted: false,
    lengthM: 150,
    maxOccupancy: 2,
    occupancyState: "FREE" as const,
    currentOccupants: [],
    protectedSeparationM: 35,
    boundarySensors: "OPTICAL RADAR DUAL",
    weather: "NORMAL" as const,
    roadCondition: "DRY" as const,
    fogDensityPercent: 20,
    visibilityMeters: 150,
    visibility: "GOOD" as const,
    movementAuthority: "AUTHORIZED" as const,
    tokenStatus: "VALID" as const,
  },
];

export const SCENARIO_LABELS: { id: ScenarioType; label: string }[] = [
  { id: "NORMAL_ROAD", label: "1. Normal Road" },
  { id: "OBJECT_AHEAD", label: "2. Object Ahead" },
  { id: "APPROACHING_OBJECT", label: "3. Approaching Target" },
  { id: "BLIND_CURVE", label: "4. Blind Curve & Fog" },
  { id: "JUNCTION_CONFLICT", label: "5. Junction Conflict" },
  { id: "FOLLOWING_TOO_CLOSE", label: "6. Close Separation" },
  { id: "CRITICAL_TTC", label: "7. Critical TTC (<2s)" },
  { id: "EMERGENCY_COLLISION", label: "8. Emergency (<1s)" },
  { id: "RADAR_FAILURE", label: "9. Radar Fault" },
  { id: "ENCODER_FAILURE", label: "10. Encoder Fault" },
  { id: "CAN_FAILURE", label: "11. CAN Bus Fault" },
  { id: "LORA_FAILURE", label: "12. LoRa Link Fault" },
  { id: "BRAKE_FAILURE", label: "13. Brake Sys Fault" },
  { id: "SENSOR_DISAGREEMENT", label: "14. Sensor Mismatch" },
];
